logging:
  level:
    root: INFO
    org:
      apache:
        kafka:
          clients: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    export:
      simple:
        enabled: true

server:
  port: 9099

spring:
  kafka:
    admin:
      client-id: basic-admin
    consumer:
      group-id: streams-showcase-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.DoubleDeserializer
      client-id: basic-consumer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.DoubleSerializer
      client-id: basic-producer
    properties:
      bootstrap.servers: localhost:9092

streamsexp:
  primitiveRecordSourceTopic: p-source
  primitiveRecordSinkTopic: p-sink
  simpleRecordSourceTopic: s-source
  simpleRecordSinkTopic: s-sink
  singlePartitionSourceTopic: 1p-source
  singlePartitionSinkTopic: 1p-sink
